# Nombres normalizados 1:1 con tu .NET
ADMIN         = "ADMINISTRADOR"
GESTOR_SRV    = "GESTOR_SERVICIO"
GESTOR_UNID   = "GESTOR_UNIDADES"
GESTOR_CONS   = "GESTOR_CONSULTA"
GESTOR_FLOTA  = "GESTOR_FLOTA"
GESTOR_FU     = "GESTOR_FLOTA_UNIDAD"

ALL_ROLES = [ADMIN, GESTOR_SRV, GESTOR_UNID, GESTOR_CONS, GESTOR_FLOTA, GESTOR_FU]
GESTOR_ROLES = [GESTOR_SRV, GESTOR_UNID, GESTOR_CONS, GESTOR_FLOTA, GESTOR_FU]
