# app/core/roles.py

# Nombres NORMALIZADOS (así quedarán en NormalizedName)
ADMIN = "ADMINISTRADOR"
GESTOR_SRV = "GESTOR_SERVICIOS"
GESTOR_UNID = "GESTOR_UNIDADES"
GESTOR_CONS = "GESTOR_CONSULTA"
GESTOR_FLOTA = "GESTOR_FLOTA"
GESTOR_FU = "GESTOR_FLOTA_UNIDAD"

GESTOR_ROLES = {
    GESTOR_SRV, GESTOR_UNID, GESTOR_CONS, GESTOR_FLOTA, GESTOR_FU
}

ALL_ROLES = {ADMIN, *GESTOR_ROLES}